### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheOnlyWayUp**

### CODE REVIEW

**Comment by TheOnlyWayUp** [comment]
the main branch is being modified, I'll make a PR for that when it's done.

**Comment by saumsy** [comment]
Hey @TheOnlyWayUp the space update is nice but the asyncio.run and loop is almost the same thing... could you please remove that?

**Comment by TheOnlyWayUp** [comment]
> Hey @TheOnlyWayUp the space update is nice but the asyncio.run and loop is almost the same thing... could you please remove that?

asyncio.run is preferred syntax for running a coroutine, especially when there isn't a running event loop already.

**Comment by saumsy** [comment]
What happened? You doing stuff or not?

**Comment by yxshv** [comment]
unnecessary stuffs

**Comment by TheOnlyWayUp** [comment]
> What happened? You doing stuff or not?

Nope, 
```py
>>> asyncio.get_event_loop()
<stdin>:1: DeprecationWarning: There is no current event loop
```
asyncio.run handles everything cleanly for you. You're just making it worse for yourself \:P

**Pull request closed without merging**
